### ISSUE TITLE
Name Change sends to the server for each character typed

### ISSUE THREAD

**Issue by tagban** [mierau/hotline#1]
Its very common for Hotline users to change names for AFK/etc other statuses. This was a bit surprising but I saw it on Nostalgia since it shows these types of changes in chat. 
<img width="486" alt="Screenshot 2024-01-02 at 12 28 47 PM" src="https://github.com/mierau/hotline/assets/7320004/8b0dede7-8df1-4e12-b805-9825d20c4843">

**Comment by mierau** [comment]
I'll test this. I was aware of this happening and never really got around to making sure it was fixed.

**Comment by mierau** [comment]
This should be fixed now. Thank you!
