### ISSUE TITLE
Chrome warns this file is suspicious and blocks download

### ISSUE THREAD

**Issue by siemvaessen** [mierau/hotline#10]
When downloading the Hotline.b11.zip file to my machine (Macbook - Sonoma 14.2.1 (23C71) it tells me the file is suspicious. Was able to proceed etc, but just so you know. I know Hotline is suspicious, but not that suspicious though!

![Screenshot 2024-02-13 at 16 23 22](https://github.com/mierau/hotline/assets/961036/0ba9bc56-5a60-4ce5-9561-eb6a8c611cd6)

**Comment by mierau** [comment]
Weird I don't use Chrome. I'll try to do some reading about why it might think this and fix it. Strange!

**Comment by tagban** [comment]
I didn't have this issue on mine. Hotline isn't suspicious and I've tested this a bit. I don't see this as a thing.

**Comment by mierau** [comment]
Going to close this out for now. I haven't been able to reproduce this myself. I mean, at the end of the day, it is just an app in a zip file which is suspicious on its own I suppose? Not sure what to do about that other than try to submit it to the App Store.

**Comment by siemvaessen** [comment]
True and sorry about the delay in my reply!
