### ISSUE TITLE
Login failed when logging in as admin

### ISSUE THREAD

**Issue by Knezzen** [mierau/hotline#13]
Hi!

Can't login using Hotline on my server running Mobius. When I look at the logs in Mobius, it looks like Hotline is sending some strange data. Logging in works using other clients on the same server.

This is what it looks like when I try to log in using GLoarbLine on my TiBook (a client based on the original Hotline Connect client sources):
```
info	Connection established	{"RemoteAddr": "1.2.3.4:49152"}
debug	Received Transaction	{"remoteAddr": "1.2.3.4:49152", "login": "username", "RequestType": "TranAgreed"}
info	Login successful	{"remoteAddr": "1.2.3.4:49152", "login": "username", "name": "nickname", "clientVersion": "197"}
debug	Received Transaction	{"remoteAddr": "1.2.3.4:49152", "login": "username", "name": "nickname", "RequestType": "tranHandleGetUserNameList"}
debug	Received Transaction	{"remoteAddr": "1.2.3.4:49152", "login": "username", "name": "nickname", "RequestType": "TranListUsers"}
debug	Received Transaction	{"remoteAddr": "1.2.3.4:49152", "login": "username", "name": "nickname", "RequestType": "TranUpdateUser"}
info	UpdateUser	{"remoteAddr": "1.2.3.4:49152", "login": "username", "name": "nickname", "login": "username"}
```

This is what it looks like when I try to log in with the same credentials using Hotline on Sonoma:
```
info	Connection established	{"RemoteAddr": "1.2.3.4:62989"}
info	Login failed	{"remoteAddr": "1.2.3.4:62989", "login": "ëîåúúåî", "clientVersion": "0000007b"}
```
The "ëîåúúåî" is what it actually sends out. Something seems to be wrong on the client side.

**Comment by vido420** [comment]
I run Badmoon the server and this also happens to me.  Using my credentials I can’t logging into my own server but I can login as guest.

**Comment by Knezzen** [comment]
> I run Badmoon the server and this also happens to me. Using my credentials I can’t logging into my own server but I can login as guest.

Same here. Guest works great of course.

**Comment by Knezzen** [comment]
Aha. I see that it's fixed in https://github.com/mierau/hotline/commit/6aad4ed3d079db171564144aa69b0431f5af669d there just haven't been a new binary released after it got committed to the master branch.

**Comment by mierau** [comment]
There have been a few releases over the past few weeks. Your issue should be fixed. Hopefully!

**Comment by mierau** [comment]
Going to close this for now as I believe this has been fixed. Let me know otherwise.
