### ISSUE TITLE
Feature request: Option double-click Tracker listing

### ISSUE THREAD

**Issue by aptonline** [mierau/hotline#16]
In the official version of Hotline, if you hold the option key and double-click a tracker listing you are given the ability to add your credentials and save a bookmark as its pre-populated with the server address.  I may have missed this in this version but unable to recreate. but find this useful.

![Screenshot 2024-05-02 at 12 58 00](https://github.com/mierau/hotline/assets/190136/8d80d770-64dd-4d07-b88f-cdee3f6d7c08)

You already have the relevant dialog in the app that's repopulated when the connection to a server times out so it's essentially just triggering this and populating the server details for saving etc.

![Screenshot 2024-05-08 at 15 23 24](https://github.com/mierau/hotline/assets/190136/a7111e5a-3b70-4b5f-8ac2-fea0260407c3)

**Comment by aptonline** [comment]
I noticed you have added something similar to this is the latest build (b19) but not specifically in the tracker listing.  The idea is by option-double clicking in a server in the tracker it will allow the server address to be pre-populated so that credentials can be added.  Useful if your server ip changes (for some reason) and you need to log back in as admin.

**Comment by mierau** [comment]
Yeah I haven't checked this one off yet because I haven't yet added what you were asking for. It's a little trickier to implement than what I added here in the toolbar. I'll get it in soon, thanks!

**Comment by mierau** [comment]
OK this ended up being easy. Will be in next build. Going to close this now. Thanks! :)
