### ISSUE TITLE
Feature Request: Contextual menu for common file actions

### ISSUE THREAD

**Issue by aptonline** [mierau/hotline#18]
It would be very handy to have a contextual menu that replicated the common file actions (Delete, Preview File, Get File Info and Download) from the main window.

![Screenshot 2024-05-09 at 16 15 48](https://github.com/mierau/hotline/assets/190136/2258609f-cc69-46d3-99a9-ce3f99105d3e)

This could also be replicated across News but don't feel this is as useful but would be consistent.

**Comment by mierau** [comment]
For sure. Will add it to the list. Thanks!

**Comment by mierau** [comment]
OK there should be a set of context menus in the next build.
