### ISSUE TITLE
Cannot add new tracker

### ISSUE THREAD

**Issue by tagban** [mierau/hotline#2]
The little + button on the servers/trackers page doesn't appear to do anything. I'm on Mac OS X Sonoma on an M1 if that helps. 

Ideally I'd want that to be able to add either a server or tracker.

**Comment by mierau** [comment]
> The little + button on the servers/trackers page doesn't appear to do anything. I'm on Mac OS X Sonoma on an M1 if that helps. 
> 
> 
> 
> Ideally I'd want that to be able to add either a server or tracker. 

It's true! I just haven't written the logic for either yet. Will probably add soon. Thanks! I'll close this issue when implemented. :)

**Comment by mierau** [comment]
Latest build replaces the plus button with a globe to connect to a server. Though you can't add trackers yet (or bookmark servers), at least the plus button (now globe) technically does something? :P

**Comment by tagban** [comment]
That works, at least now I can add servers. :) Thank you

**Comment by mierau** [comment]
You should be able to add both trackers and bookmark servers in the latest build. They are stored in Keychain for now. I may change this in the future. Going for security but I don't like how you're asked for your keychain password on launch... hmm. Though you do get syncing across devices which is nice.
