### ISSUE TITLE
Upload functionality?

### ISSUE THREAD

**Issue by gingerbeardman** [mierau/hotline#28]
I don't know if it's my slowly aging brain and memory, or me forgetting how Hotline works.

But I can't upload files to a server Upload folder.

Cheers!

**Comment by mierau** [comment]
This feature is almost ready. Just putting the finishing touches on it. :)

**Comment by mierau** [comment]
Okay this should be working in the latest build. Closing this out. Adding support for folder uploads at some point.

**Comment by gingerbeardman** [comment]
Thanks Dustin
