### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by aptonline** [mierau/hotline#37]
I've noticed when logging into some servers the Accounts options are available which shows users name, login and file system maintenance options even though I am not an admin on that server.  Yes the password is not visible but I can partially see some credentials which could be considered a security concern.  Just flagging 👍🏼.

<img width="235" alt="Screenshot 2024-09-30 at 16 43 33" src="https://github.com/user-attachments/assets/2faa579c-8abb-47ef-816c-c384c6a3a600">

**Comment by mierau** [comment]
Yeah this is because they have this visible to guests for some reason. Up to the admin of the server.
