### ISSUE TITLE
Connection attempt hangs with no traffic observed

### ISSUE THREAD

**Issue by jhalter** [mierau/hotline#4]
Hi 👋, 

In 1.0beta6 I'm not able to connect to any servers from the tracker list.  With Wireshark running, I don't see any traffic sent to the server:

<img width="1191" alt="Screenshot 2024-01-04 at 1 55 56 PM" src="https://github.com/mierau/hotline/assets/868228/65f245f6-1c37-450b-bbf5-9a72183188db">

As a sanity check I built the app from the 1.0beta5 tag and all was well.  Possible regression?

Thanks for all your work on this project!

**Comment by mierau** [comment]
I'll take a look I'm doing a bunch more work in that code as I was seeing some issues with passing login info through bindings.

**Comment by mierau** [comment]
Let me know if beta7 fixes this for you at all. :\
I've only seen this with servers that require server agreement before connection finishes (something I'll need to add support for eventually). Does Mobius have this feature?

**Comment by jhalter** [comment]
I'm still seeing the same connection hang behavior in beta7.

Mobius supports both the 1.2.3 agreement-less login flow and the 1.5+ flow that expects a reply to the agreement, which I'd maybe be suspicious of, except that I'm not even seeing the TCP handshake on 5500 reach the server when the client hangs.  So it seems like the client isn't reaching a point where it tries to establish a TCP connection.

Some data points that I don't understand:
* I can consistently connect to my local dev server on 127.0.0.1:5500 from 1.0beta6 or 7
* I can never connect to any server that isn't localhost, either by specifying the IP or clicking on the tracker listings
* 1.0beta5 consistently works, which seemingly rules out environmental oddities on my end (I think)

**Comment by mierau** [comment]
I think I know what changed. I believe I enabled fast TCP connections in b6. I think. I'll check in the morning and revert if so. That's what I get for messing around. 😅

**Comment by techsuppork** [comment]
I'm seeing the same behavior. I'm happy to capture packets if that helps.

**Comment by mierau** [comment]
Thanks! I'll be posting a new build maybe tonight that hopefully fixes the issue. I wish Apple had better documentation on its socket library NWConnection. It's extremely sparse at the moment.

**Comment by techsuppork** [comment]
Just an update. When logging in, the progress bar never completes, but I am able to chat and see other's chats. I can't see the user list and have no ability to see files or news.

**Comment by mierau** [comment]
Just published a new release. Let me know if you're still seeing this. I was seeing some weirdness connecting to the public server System 7 Today and fixed it.

**Comment by jhalter** [comment]
The new build looks good to me. Thanks!! 🎉

**Comment by techsuppork** [comment]
New build works great on my 1.9 server, works great on Mobius servers, but I still can't complete the login process on my 1.2.3 server. Feel free to test it out here theabode.ath.cx:5500

**Comment by mierau** [comment]
I'm currently not handling the flow where a server requires people agree to the agreement before continuing. Need to think on how to handle this a bit. Thanks!

**Comment by tagban** [comment]
Id treat it as auto agree to skip it by with the caveat that will
eventually be working post beta world.

**Comment by mierau** [comment]
Going to mark this issue as closed for now. Thanks everyone. Created a new issue for agreement accepting. Auto-accepting may be the first version, I agree. I think I specifically didn't implement that because if someone is requiring agreement acceptance, there is probably a reason for it. :)
