### ISSUE TITLE
Request: < macOS 14.x compatibility

### ISSUE THREAD

**Issue by vga-256** [mierau/hotline#9]
I'm not sure what the project's goals are for compatibility, but Sonoma-only is a project killer in my household. I'd love to be able to run a client on my various machines running Big Sur.

**Comment by mierau** [comment]
I'll need to think on it a bit. My goal has been use the latest tech so it's easier to maintain. If the community wants to get in and try to get this working on older systems I'm all for it, but, I'm not sure I can justify the effort right now. :(

**Comment by aptonline** [comment]
> I'm not sure what the project's goals are for compatibility, but Sonoma-only is a project killer in my household. I'd love to be able to run a client on my various machines running Big Sur.

I’d support that, yes I am lucky enough to have Sonoma on a relatively new device but being able to run it on older, retro kit, would be a bonus.

The work you are doing to document and refactor the original protocols into modern accessible will help.  Make there’s an opportunity to fork the project here 🤔

**Comment by vga-256** [comment]
Sounds good. I'll get to work on compiling it on Big Sur for now, and see how far back I can build compatibility.

**Comment by vga-256** [comment]
Before I can begin working through compilation in Xcode 13.x, I will need someone to switch the Xcode Project Format from 15.x to at least 13.x, or even earlier.

**Comment by godzfire** [comment]
Stumbled upon this trying to find if there's any kind of modern client for Hotline still out there. Happy to find this, but then sad when I saw it's 14 only. I agree, that's a dealbreaker for me as I'm on Mont 12 and can't upgrade.

Please give consideration into putting out a version that's compatible with the earliest version of MacOS as possible.

**Comment by mierau** [comment]
I'm going to close this out for now. I don't see this happening sorry. SwiftUI is just too new and the entire app is built with it and as WWDC approaches I suspect I'm going to watch to use some of those new features to make the client more functional/nicer to use.

**Comment by godzfire** [comment]
That's really disappointing to hear since as it stands, there is no working Hotline client available for Intel 64 Macs. Having at least OS 11, 12, and 13 would solve that gap. I literally can't upgrade. :-(

**Comment by mierau** [comment]
Well, I shouldn't say never. It is open source after all. There are just so many bugs in earlier versions of SwiftUI that I think that it would require a rewrite in AppKit which I'm just unwilling to do as it would slow the project down and make it less future proof. Sorry. :(
